# [dbo].[DemoUser]

In [0]:
USE [Demo_DotNetCore5.0MVC]
GO

In [0]:
/****** Object:  Table [dbo].[DemoUser]    Script Date: 5/8/2022 5:12:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DemoUser](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Email] [nchar](100) NULL,
	[Phone] [nchar](14) NULL,
	[Address] [nvarchar](200) NULL,
 CONSTRAINT [PK_DemoUser] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

In [0]:
SET IDENTITY_INSERT [dbo].[DemoUser] ON 
INSERT [dbo].[DemoUser] ([Id], [Name], [Email], [Phone], [Address]) VALUES (1, N'Quan', N'teo@gmail.com                                                                                       ', N'0909222333    ', N'abc đường D Khu B, Tp ABC')
INSERT [dbo].[DemoUser] ([Id], [Name], [Email], [Phone], [Address]) VALUES (2, N'Nguyet', N'tao@gmail.com                                                                                       ', N'0909111222    ', N'haha đường hihi, Tp Alabasta')
SET IDENTITY_INSERT [dbo].[DemoUser] OFF
GO